---
name: ifgen
version: "{{major}}.{{minor}}.{{patch}}"
description: An interface generator for distributed computing.
entry: {{entry}}
time_command: true

ci_local:
  - "- uses: seanmiddleditch/gha-setup-ninja@master"
  - "  with: {version: 1.11.1}"
  - "  if: matrix.system == 'ubuntu-latest'"

  - "- run: sudo apt-get install gcc-13 g++-13 clang-18 clang-format-18"
  - "  if: matrix.system == 'ubuntu-latest'"
  - "- run: pip${{'{{matrix.python-version}}'}} install yambs"

requirements:
  - runtimepy>=2.13.3
  - vcorelib>=3.0.0
  - "pytest<8.0.0; sys_platform == 'win32'"

dev_requirements:
  - pytest-cov
  - setuptools-wrapper
  - types-setuptools
  - yambs>=3.0.4

commands:
  - name: gen
    description: generate interfaces
  - name: svd
    description: process CMSIS-SVD files
