---
name: Python Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
  GITHUB_API_TOKEN: ${{secrets.API_TOKEN}}

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.11"
        system:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      PYTHON_VERSION: ${{matrix.python-version}}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@main
        with:
          python-version: ${{matrix.python-version}}
          cache: pip

      - run: pip${{matrix.python-version}} install vmklib

      # Begin project-specific setup.
      - uses: seanmiddleditch/gha-setup-ninja@master
        with: {version: 1.11.1}
        if: matrix.system == 'ubuntu-latest'
      - run: sudo apt-get install gcc-12 g++-12 clang-15 clang-format-15
        if: matrix.system == 'ubuntu-latest'
      - run: pip${{matrix.python-version}} install yambs
      # End project-specific setup.

      - run: mk python-sa-types

      - name: lint and build
        run: mk python-lint python-sa yaml python-build-once
        env:
          PY_LINT_MYPY_EXTRA_ARGS: --no-incremental

      - run: mk docs
        if: |
          matrix.python-version == '3.11'
          && matrix.system == 'ubuntu-latest'

      - run: mk python-test
        env:
          PY_TEST_EXTRA_ARGS: --cov-report=xml

      - uses: codecov/codecov-action@v3

      - run: mk pypi-upload-ci
        env:
          TWINE_USERNAME: __token__
        if: |
          matrix.python-version == '3.11'
          && matrix.system == 'ubuntu-latest'
          && env.TWINE_PASSWORD != ''
          && github.ref_name == 'master'

      - run: |
          mk python-release owner=vkottler \
                            repo=ifgen version=2.5.0
        if: |
          matrix.python-version == '3.11'
          && matrix.system == 'ubuntu-latest'
          && env.GITHUB_API_TOKEN != ''
          && github.ref_name == 'master'
